### ISSUE TITLE
Syntax Error: Expected Name, found }

### ISSUE THREAD

**Issue by abzalzhumabaev** [joselfonseca/lighthouse-graphql-passport-auth#1]
After installation and setting variables to .env, getting error on /graphql:
Syntax Error: Expected Name, found }
![screen shot 2019-02-12 at 9 37 38 pm](https://user-images.githubusercontent.com/10655757/52647245-8f325980-2f0e-11e9-80e6-6fadc0dc1cc5.png)

**Comment by joselfonseca** [comment]
Hello @abzalzhumabaev was just coming to see this, did you find the problem?

**Comment by abzalzhumabaev** [comment]
@joselfonseca, yes, error was in graphql schema's part, nothing deal with package, sorry for misleading issue

**Comment by joselfonseca** [comment]
@abzalzhumabaev Oh not a problem, let me know if you need anything else. Thanks!
