### ISSUE TITLE
Use different field for login

### ISSUE THREAD

**Issue by idrislab** [joselfonseca/lighthouse-graphql-passport-auth#10]
Hi,

Is there an easy way to use a different field other than _username_, in my case _email_, for login? Right now it seems to be hardcoded for _username_.

**Comment by joselfonseca** [comment]
You mean in the Schema? https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/graphql/auth.graphql#L2 This is because the Passport field is `username` regardless of the database field used as username.

https://laravel.com/docs/5.8/passport#requesting-password-grant-tokens

**Comment by idrislab** [comment]
@joselfonseca thanks. Btw, great plugin.

**Comment by joselfonseca** [comment]
@idrislab Thank you for using it, I will close this as is not an issue. Any other question feel free to ask and mark the issue as question if possible. Thanks!
