### ISSUE TITLE
Registration BUG

### ISSUE THREAD

**Issue by stephenjason89** [joselfonseca/lighthouse-graphql-passport-auth#103]
Please make your registration.php resolve function
include exception of directive before model save because it is giving error unknown directive field
Thank you

    public function resolve($rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo)
    {
        $model = app(config('auth.providers.users.model'));
        $input = collect($args)->except(['password_confirmation','directive'])->toArray();
        $input['password'] = Hash::make($input['password']);
        $model->fill($input);
        $model->save();
... //the rest of the code
}

**Comment by joselfonseca** [comment]
You can also make a PR. We have not encounter this issue and is probably faster to merge a PR than us trying to replicate it.

**Comment by stephenjason89** [comment]
Thank you will do now.

**Comment by stephenjason89** [comment]
While editing the fork i just realized the code was not there.
It turned out that my register.php file from composer was so I deleted my vendor file and composer clearcache
redownloaded everything on version 4.1.12

but I still have this register.php 
is this from the old versions?
why am I getting this instead the one from the master branch



namespace Joselfonseca\LighthouseGraphQLPassport\GraphQL\Mutations;

use GraphQL\Type\Definition\ResolveInfo;
use Illuminate\Auth\Events\Registered;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Support\Facades\Hash;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;

class Register extends BaseAuthResolver
{
    /**
     * @param $rootValue
     * @param array                                                    $args
     * @param \Nuwave\Lighthouse\Support\Contracts\GraphQLContext|null $context
     * @param \GraphQL\Type\Definition\ResolveInfo                     $resolveInfo
     *
     * @throws \Exception
     *
     * @return array
     */
    public function resolve($rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo)
    {
        $model = app(config('auth.providers.users.model'));
        $input = collect($args)->except('password_confirmation')->toArray();
        $input['password'] = Hash::make($input['password']);
        $model->fill($input);
        $model->save();
        if ($model instanceof MustVerifyEmail) {
            $model->sendEmailVerificationNotification();

            event(new Registered($model));

            return [
                'tokens' => [],
                'status' => 'MUST_VERIFY_EMAIL',
            ];
        }
        $credentials = $this->buildCredentials([
            'username' => $args[config('lighthouse-graphql-passport.username')],
            'password' => $args['password'],
        ]);
        $user = $model->where(config('lighthouse-graphql-passport.username'), $args[config('lighthouse-graphql-passport.username')])->first();
        $response = $this->makeRequest($credentials);
        $response['user'] = $user;
        event(new Registered($user));

        return [
            'tokens' => $response,
            'status' => 'SUCCESS',
        ];
    }
}

**Comment by stephenjason89** [comment]
Yes i can confirm that the issue has been resolved on the master branch
