### ISSUE TITLE
Please add support for passport v10

### ISSUE THREAD

**Issue by stephenjason89** [joselfonseca/lighthouse-graphql-passport-auth#108]
I'm currently upgrading to laravel 8 and it would be nice if this include support for passport 10
and socialite 5.0

thank you

**Comment by joselfonseca** [comment]
hey there @stephenjason89, it is in my radar, Laravel 8 just came out and we are not upgrading our apps yet, we are planning to add the support for this on 5.0 which is the next release scheduled for the 18th. 

PRs are welcome!

**Comment by stephenjason89** [comment]
Thank you for the update. Will try to do a PR once it is released. 

side note: 
            is multiple social account integration per user gonna be included?
                 using socialLogin, it only assigns 1 provider per user.

What I did on my end was to create another table social_accounts and made it (belongsTo a user) (user hasMany social_accounts)

**Comment by joselfonseca** [comment]
Need to wait for https://github.com/nuwave/lighthouse to add Laravel 8 support before we can upgrade.

**Comment by stephenjason89** [comment]
Thank you :)

**Comment by joselfonseca** [comment]
I re open the issue for tracking purposes and to keep the reminder to update.

**Comment by joselfonseca** [comment]
<img width="913" alt="Screen Shot 2020-09-23 at 9 26 42 AM" src="https://user-images.githubusercontent.com/2046653/94026204-fbc63900-fd7e-11ea-9f70-af609b162f5f.png">
It will be harder than I thought
