### ISSUE TITLE
Authentication fails no matter what

### ISSUE THREAD

**Issue by RickMartens** [joselfonseca/lighthouse-graphql-passport-auth#111]
The login function always returns a authentication exception explaining the password or username is incorrect. The .env file contains the right client and client key, I've followed your guide on https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5 and triple checked if I've done every check. 
A direct request to the server, trying to log in through Laravel Passport does work with the same login credentials.

**Comment by joselfonseca** [comment]
Can you provide a repo with the replicated issue? We are running this in many projects without any issues.

**Comment by RickMartens** [comment]
A `php artisan config:cache` fixed the problem, thanks for the quick reply anyways!
