### ISSUE TITLE
Using multiple Clients

### ISSUE THREAD

**Issue by th3error** [joselfonseca/lighthouse-graphql-passport-auth#112]
Hi,

Is there a way to use multiple passport clients which are associated with multiple providers/guards? I'm trying to implement Multi-Auth where I have multiple tables to authenticate from. Each table is linked to a different user model.

I have everything setup except allowing for multiple 'client_id' and 'client_secret' (lighthouse-graphql-passport.php)

This comment here makes me believe there is no native suppot for the above:
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/issues/65#issuecomment-587446888

Any idea what files I need to hack in order to achieve this?

**Comment by joselfonseca** [comment]
If I am not mistaken, you can modify the GraphQL schema to receive the client_id and client_secret in the mutation and it will use it. Regarding the multiple models you will have to set that up in runtime from a request parameter.

**Comment by joselfonseca** [comment]
![image](https://user-images.githubusercontent.com/2046653/94349032-8ec4d480-0006-11eb-8df1-74ab6fac52be.jpeg)

Yes you can send that in the mutation, that is the line. Sorry for the screenshot I am mobile right now. All you have to do is update the GraphQL schema to accept the additional parameters.
