### ISSUE TITLE
how to verify phone number instead of an email

### ISSUE THREAD

**Issue by seosazi** [joselfonseca/lighthouse-graphql-passport-auth#114]
hi
in my program, we don't need email and work with phone number. before I implement this, I want to know that we have a ready solution for this work, right?
thanks

**Comment by joselfonseca** [comment]
You can Update the schema to receive the phone number and implement this method in the user model

https://laravel.com/docs/7.x/passport#customizing-the-username-field

**Comment by seosazi** [comment]
thanks a lot, 
My problem is that how can create token after that phone number verified?

**Comment by joselfonseca** [comment]
After you implement that method and it returns the user object the flow continues normally and the token will be issued, that method just finds the user object by using a custom query like looking for it by phone number. the rest of the flow stays the same.
