### ISSUE TITLE
SendsPasswordResetEmails does not exist in Laravel 8

### ISSUE THREAD

**Issue by webard** [joselfonseca/lighthouse-graphql-passport-auth#120]
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/3da831efbbab68bf0c3b859c7641f4c2300ca060/src/GraphQL/Mutations/ForgotPassword.php#L13

**Comment by joselfonseca** [comment]
hello @webard 

Can you please check that `"laravel/ui": "^3.0",` is installed. It should be a dependency in the package and that is what brings the trait.

**Comment by joselfonseca** [comment]
Although I may be wrong about that. Since is Illuminate foundation. I'll take a look later today.

**Comment by webard** [comment]
Unfortunately that class does not exist in Laravel/ui. When I removed this trait from usage, mail was sent correctly but need to declare broker() method in RefreshToken class,  because was present in SendsPasswordResetEmails.
