### ISSUE TITLE
Throw exception or error instead of custom response on failure to send reset-password email

### ISSUE THREAD

**Issue by FreekVR** [joselfonseca/lighthouse-graphql-passport-auth#127]
When sending the reset password e-mail fails, currently the following JSON response is sent back as graphql data:

```php
return [
            'status'  => 'EMAIL_NOT_SENT',
            'message' => __($response),
        ];
```

I would suggest throwing an Exception or Error here, which will be formatted by lighthouse according to the GraphQL spec, which would help in a frontend app that only responds to this errors object to show errors by default. Currently I'd have to add a custom front-end handler for this use case to show feedback to the user.

**Comment by joselfonseca** [comment]
This is a good catch. For some reason I though I did that already. I'll make it happen. Thanks @FreekVR

**Comment by joselfonseca** [comment]
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/5.2.1

**Comment by FreekVR** [comment]
That was quick -- thanks :)!
