### ISSUE TITLE
Route [password.reset] not defined.

### ISSUE THREAD

**Issue by ryanscherler** [joselfonseca/lighthouse-graphql-passport-auth#13]
Hi Jose,

I first want to thank you SO much for creating this package - its a great start to authentication via Lighthouse / GraphQL. The issue I am running into is password resets. It seems if I dont define a route like the following:
```php
Route::post('password/reset', 'Joselfonseca\LighthouseGraphQLPassport\GraphQL\Mutations\ForgotPassword@resolve')->name('password.reset');
```

I get a response:

```json
{
  "errors": [
    {
      "debugMessage": "Route [password.reset] not defined.",
      "message": "Internal server error",
...
```

Is there something in my `config/auth.php` under passwords that I need to update to ensure I dont have to define a route / controller for this?

```php
    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
```

**Comment by ryanscherler** [comment]
Looks like I just needed to override the default notification for resetting passwords. There is a reference to the route when building the email for the notification in the default. 

```php
    /**
     * Build the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        if (static::$toMailCallback) {
            return call_user_func(static::$toMailCallback, $notifiable, $this->token);
        }

        return (new MailMessage)
            ->subject(Lang::getFromJson('Reset Password Notification'))
            ->line(Lang::getFromJson('You are receiving this email because we received a password reset request for your account.'))
            ->action(Lang::getFromJson('Reset Password'), url(config('app.url').route('password.reset', ['token' => $this->token, 'email' => $notifiable->getEmailForPasswordReset()], false))) // --------------->Here is the issue
            ->line(Lang::getFromJson('This password reset link will expire in :count minutes.', ['count' => config('auth.passwords.users.expire')]))
            ->line(Lang::getFromJson('If you did not request a password reset, no further action is required.'));
    }
```

**Comment by joselfonseca** [comment]
Thanks for finding the issue! I was about to look at this. Happy coding!

**Comment by eli007s** [comment]
@ryanscherler I'm having the same issue, I don't know as much about Laravel as others so your solution left me with ore questions than answers. Can you please tell me what file it is that your editing? I'm running Laravel 8 at the moment.

**Comment by asilvabe** [comment]
I had this same problem and I solved it in a very simple way.

In the `App\Providers\AuthServiceProvider` service I added `createUrlUsing` method provided by the `ResetPassword` class:

```php
<?php

namespace App\Providers;

use Laravel\Passport\Passport;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Illuminate\Auth\Notifications\ResetPassword;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Passport::routes();

        ResetPassword::createUrlUsing(function ($user, string $token) {
            return 'https://example.com/reset-password?token='.$token;  // Here is your custom url
        });
    }
}
```

Official documentation
https://laravel.com/docs/8.x/passwords#reset-link-customization

**Comment by depthoffocus** [comment]
@asilvabe that is super neat :-) Thanks for finding it.

**Comment by joselfonseca** [comment]
Hello all, thanks for the answers here, for a little bit of context, we usually create the notification for password reset or customize the view to use a app url scheme since we mostly use this as a backend for mobile apps. Since we always do this we have never run into this issue and the times I've seen it is a matter of updating the email template or notification. 
That url or route is for a web app, usually comes in the breeze or auth scaffold so maybe that is why we missed it, the thing is, that the notification part is out of the scope of the package since it leaves in Laravel core or your app. Any ideas for improving this are welcome! Maybe we just need to document this somewhere in the docs.

**Comment by xx1196** [comment]
@joselfonseca, i dont understand, why is the solution for this?

**Comment by xx1196** [comment]
> I had this same problem and I solved it in a very simple way.
> 
> In the `App\Providers\AuthServiceProvider` service I added `createUrlUsing` method provided by the `ResetPassword` class:
> 
> ```
> <?php
> 
> namespace App\Providers;
> 
> use Laravel\Passport\Passport;
> use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
> use Illuminate\Support\Facades\Gate;
> use Illuminate\Auth\Notifications\ResetPassword;
> 
> class AuthServiceProvider extends ServiceProvider
> {
>     /**
>      * The policy mappings for the application.
>      *
>      * @var array
>      */
>     protected $policies = [
>         // 'App\Models\Model' => 'App\Policies\ModelPolicy',
>     ];
> 
>     /**
>      * Register any authentication / authorization services.
>      *
>      * @return void
>      */
>     public function boot()
>     {
>         $this->registerPolicies();
> 
>         Passport::routes();
> 
>         ResetPassword::createUrlUsing(function ($user, string $token) {
>             return 'https://example.com/reset-password?token='.$token;  // Here is your custom url
>         });
>     }
> }
> ```
> 
> Official documentation
> https://laravel.com/docs/8.x/passwords#reset-link-customization

i have this error
`debugMessage": "Cannot send message without a sender address",`

**Comment by depthoffocus** [comment]
> i have this error
> `debugMessage": "Cannot send message without a sender address",`

This is likely unconnected. You may just need to configure that. For example in config/mail.php you will have lines like:

```php
    'from' => [
        'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
        'name' => env('MAIL_FROM_NAME', 'Example'),
    ],
```

So you could just set `MAIL_FROM_NAME` and `MAIL_FROM_ADDRESS` in `.env`.

**Comment by xx1196** [comment]
in my case my front is react, in laravel i add this lines in `AuthServiceProvider`

`ResetPassword::createUrlUsing(function ($user, string $token) {
            return env('APP_URL_FRONT') . '/reset-password?token='.$token;
        });`

and in my .env i have this variable `APP_URL_FRONT=localhost:3000`<-- add you url front

**Comment by jana79** [comment]
Hi! I have tried to implement the solutions provided and I get it to send the email, but on the front I would like not to ask for the email again. Just the password and password confirmation. How could I send the user's email at the same time as the token? Or maybe the token is only associated with that email? Thank you so much!
