### ISSUE TITLE
I can't use this package with lighthouse 5

### ISSUE THREAD

**Issue by elendil1979** [joselfonseca/lighthouse-graphql-passport-auth#131]
If I configure composer.json with   "nuwave/lighthouse": "5.*",

I got this problem when run composer update

 Problem 1
    - joselfonseca/lighthouse-graphql-passport-auth[5.0.0, ..., 5.0.x-dev] require nuwave/lighthouse ^3.0|^4.0 -> found nuwave/lighthouse[v3.0-alpha.1, ..., 3.x-dev, v4.0-alpha.1, ..., 4.x-dev] but it conflicts with your root composer.json require (5.*).
    - joselfonseca/lighthouse-graphql-passport-auth[5.2.0, ..., 5.2.x-dev] require nuwave/lighthouse ^4.17 -> found nuwave/lighthouse[v4.17.0, v4.18.0, 4.x-dev] but it conflicts with your root composer.json require (5.*).
    - joselfonseca/lighthouse-graphql-passport-auth[5.1.0, ..., 5.1.2] require nuwave/lighthouse ^4.0 -> found nuwave/lighthouse[v4.0-alpha.1, ..., 4.x-dev] but it conflicts with your root composer.json require (5.*).
    - Root composer.json requires joselfonseca/lighthouse-graphql-passport-auth ^5.0 -> satisfiable by joselfonseca/lighthouse-graphql-passport-auth[5.0.0, ..., 5.2.x-dev]. 

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Then I must set   "nuwave/lighthouse": "4.*",

Maybe the cause is your own composer.json, 

Thanks

**Comment by joselfonseca** [comment]
Hello, yes I am still working on lighthouse 5.0 compatibility. I should have it done this week. 

Enviado desde mi iPhone

**Comment by joselfonseca** [comment]
@elendil1979 This PR should fix it. I will tag a new version in a bit.

**Comment by elendil1979** [comment]
Thank you so much
