### ISSUE TITLE
No directive found for `middleware`

### ISSUE THREAD

**Issue by Fitmavincent** [joselfonseca/lighthouse-graphql-passport-auth#133]
After following the tutorial, and try to query and the error returns: No directive found for `middleware`. Is anything changes or missing some configs?

**Comment by Fitmavincent** [comment]
Oh, Jeez, tutorials are outdated

**Comment by joselfonseca** [comment]
Hi @Fitmavincent, it should not be outdated unless you are referring to something different to https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5 can you please tell me what lighthouse version you are using and what version of the package please?

**Comment by joselfonseca** [comment]
Wait, I just found it. It seems that I missed that part. Sorry about that. I am updating it right now.

**Comment by joselfonseca** [comment]
Updated it.
```graphql
users: [User!]! @guard(with: ["api"]) @paginate(type: "paginator" model: "App\\User")
```
