### ISSUE TITLE
Latest version 6.0 migration error

### ISSUE THREAD

**Issue by stephenjason89** [joselfonseca/lighthouse-graphql-passport-auth#138]
PHP 7.4
Laravel 8
Doing php artisan migrate:fresh throws this error

SQLSTATE[HY000]: General error: 1005 Can't create table `foodat`.`social_providers` (errno: 150
"Foreign key constraint is incorrectly formed") (SQL: alter table `social_providers` add constrain
t `social_providers_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete c
ascade)

**Comment by stephenjason89** [comment]
You should change

            $table->bigInteger('user_id');
to
            $table->unsignedBigInteger('user_id');

**Comment by joselfonseca** [comment]
Thank you, PR merged.
