### ISSUE TITLE
Schema documentation missing UpdatePassword argument "old_password"

### ISSUE THREAD

**Issue by SirLamer** [joselfonseca/lighthouse-graphql-passport-auth#147]
The schema documentation here:

https://lighthouse-php-auth.com/docs/default-schema/

Differs from the current actual schema here:

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/df888a62aaf3ede59c522dbd1cce4db143aac018/graphql/auth.graphql

UpdatePassword input has an additional argument "old_password" not in documentation.
```graphql
input UpdatePassword {
    old_password: String!
    password: String! @rules(apply: ["required", "confirmed", "min:8"])
    password_confirmation: String!
}
```

**Comment by joselfonseca** [comment]
Thanks for this! I'll update the docs.

**Comment by joselfonseca** [comment]
Updated 

https://lighthouse-php-auth.com/docs/default-schema/
