### ISSUE TITLE
use username instead of use email to login issue

### ISSUE THREAD

**Issue by kelvin6365** [joselfonseca/lighthouse-graphql-passport-auth#15]
Hi,
i have add this function in App/User.php

> public function findForPassport($username)
>     {
>         return $this->where('username', $username)->first();
>     }

Confirm have the user data.
but there have error return:
"debugMessage": "No query results for model [App\\User]."

in joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/Login.php:

> public function resolve($rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo)
>     {
>         $credentials = $this->buildCredentials($args);
>         $response = $this->makeRequest($credentials);
>         **$user = app(config('auth.providers.users.model'))->where('email', $args['data']['username'])->firstOrFail();** _**<-after i delete this line**_
>         ** $response['user'] = $user;**   _**<-after i delete this line**_
>         return $response;
>     }

It will work fine. But this not seems to be a good way.
Any suggestion?

**Comment by joselfonseca** [comment]
@kelvin6365 Thanks for reporting this I Will add a config var for that portion so you can say what is the column to look for. I'll work on this tomorrow.

**Comment by joselfonseca** [comment]
@kelvin6365 Please see https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/1.3.2

**Comment by kelvin6365** [comment]
thanks

**Comment by silasrm** [comment]
Hi,

If "username" is a field, change the `'username' => 'phone',` in _config/lighthouse-graphql-passport.php_ and implement _findForPassport_ in your authentication model:

```php
    public function findForPassport($username) {
        return $this->query()->where('phone', $username)->first();
    }
```

See: https://laravel.com/docs/7.x/passport#customizing-the-username-field
