### ISSUE TITLE
How to do CSRF Token Validation?

### ISSUE THREAD

**Issue by NoumanAhmad-Braqsol** [joselfonseca/lighthouse-graphql-passport-auth#153]
As i have read the documentation here is nothing explain abut CSRF token. How we implement CSRF token verification in 
lighthouse-graphql-passport-auth

**Comment by joselfonseca** [comment]
Hello @NoumanAhmad-Braqsol thanks for the question.

It depends how you want to use it, it feels a little out of scope for the package but you could add the middleware to lighthouse middleware stack and then validate it in every request.

https://lighthouse-php.com/5/security/csrf.html here is the documentation on lighthouse about that.
