### ISSUE TITLE
Laravel Passport Version 11

### ISSUE THREAD

**Issue by alMWI** [joselfonseca/lighthouse-graphql-passport-auth#156]
Hello,

We are updating our composer packages using the new `composer bump` and `composer outdated` commands from composer v2.4.1.

The `composer outdated` output shows 

```
Direct dependencies required in composer.json:
laravel/passport               v10.4.1 v11.0.0 Laravel Passport provides OAuth2 server support to Laravel.
```

Your `composer.json` file shows that it is using `"laravel/passort": "^9.0 || ^10.0"`. Is it possible for your package to support Laravel Passport Version 11?

**Comment by joselfonseca** [comment]
Still having issues finding the time to do this. a PR is welcome!

**Comment by joselfonseca** [comment]
Should be good in https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/8.0.0
