### ISSUE TITLE
Schema null config

### ISSUE THREAD

**Issue by dali546** [joselfonseca/lighthouse-graphql-passport-auth#16]
I had trouble setting this up at first, till I realised my problem.

if in the config file the schema is left as `null`, I think it is calling the `default` schema located in the vendor directory.

This may be a flaw or how it should be but it really pestered me. My default entry point for Lighthouse is defined in `lighthouse.php` config. and from there I would import other Schema

The issue I faced was that your "vendor" schema was being registered with graphql, causing a conflict with my User Model (which doesnt have a name field etc etc)

SOLUTION: When publishing the config, if the schema is set to null, please point it to lighthouse configs default schema, as this causes conflicts

Steps to Reproduce
Steps to reproduce
1. Install laravel/passport with Laravel instructions.
2. `run composer require joselfonseca/lighthouse-graphql-passport-auth`
3. Add to Env
PASSPORT_CLIENT_ID=
PASSPORT_CLIENT_SECRET=
4. Publish Schema and Config: `php artisan vendor:publish --provider="Joselfonseca\LighthouseGraphQLPassport\Providers\LighthouseGraphQLPassportServiceProvider"`
5. Remove `type User` from auth.graphql
6. `php artisan lighthouse:print-schema still shows original auth schema`

Result - prints out generated Schema based on your "default" schema which is located inside vendor.
```
type User {
  id: ID!
  name: String!
  email: String!
}
```
this was printed out in the schema, which is your default. 

Expected Result - Fallback to my default schema defined in `lighthouse.php`
```
type User {
  id: ID!
  username: String!
  email: String!
  events: [Event!]!
  profile: Profile
}
```

**Comment by dali546** [comment]
Workaround:

I did bypass this by modifying `lighthouse-graphql-passport.php` config:
` 'schema' => config('lighthouse.schema.register'),`

This will then use the lighthouse default schema.

There was one issue though. If the default schema in `lighthouse.php` is `auth.graphql` I get the following error
```
   GraphQL\Error\InvariantViolation  : The root Query type must be present in the schema.

  at /mnt/data/DATA/Community/Community-Server/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php:82
    78|             }
    79|         }
    80| 
    81|         if (empty($queryType)) {
  > 82|             throw new InvariantViolation(
    83|                 'The root Query type must be present in the schema.'
    84|             );
    85|         }
    86| 

  Exception trace:

  1   Nuwave\Lighthouse\Schema\SchemaBuilder::build(Object(Nuwave\Lighthouse\Schema\AST\DocumentAST))
      /mnt/data/DATA/Community/Community-Server/vendor/nuwave/lighthouse/src/GraphQL.php:242
```

The workaround to that was to use my normal `schema.graphql` and import `auth.graphql` to it.

**Comment by joselfonseca** [comment]
Hello the and thanks for the question.

So you can define your own schema by setting the file path in your config, when you publish the package config also the default schema is published so you can set the type to what ever you need. This is demonstrated in this article

https://ditecnologia.com/2019/06/24/graphql-auth-with-passport-and-lighthouse-php/

The reason for the schema to be registered and use all those defaults is for convenience, but it is also fully customizable as you can see in the article.

Let me know if that answer your question to close this issue or if you need more guidance in your specific use case.

Thanks!

**Comment by dali546** [comment]
Yes it is ok to close. The issue I was facing is that I went ahead and created my own schema, but failed to update the config. 

My assumption was that if i published the schema and config, the config should automatically use my schema. I see now after re reading the readme it does say the config should be updated. good to close

**Comment by mustafa-kahraman** [comment]
If you don't have **Mutation type** at your master schema file... you can NOT extend your schema with Auth schema cuz it has **extend type Mutation** type which there is nothing to extend...
