### ISSUE TITLE
Laravel 10 and PHP Lighthouse 6 support

### ISSUE THREAD

**Issue by elendil1979** [joselfonseca/lighthouse-graphql-passport-auth#164]
Hello,

Do you plan to add support for Laravel 10 and PHP Lighthouse 6? recently both are updated and if you apply this update this package has dependency issues.

Laravel 10 require "laravel/passport": "^11.0" and this addon require "laravel/passport: "^9.0"

This is the message from **composer update**

Problem 1
    - joselfonseca/lighthouse-graphql-passport-auth[6.0.0, ..., 6.0.2] require laravel/passport ^9.0 || ^10.0 -> found laravel/passport[v9.0.0, ..., v9.4.0, v10.0.0, ..., v10.4.2] but it conflicts with your root composer.json require (^11.0).
    - Root composer.json requires joselfonseca/lighthouse-graphql-passport-auth ^6.0 -> satisfiable by joselfonseca/lighthouse-graphql-passport-auth[6.0.0, 6.0.1, 6.0.2].

Thank you very much in advance

Hola,

¿tienes pensado agregar soporte para Laravel 10 y PHP Lighthouse 6? recientemente ambos están actualizados y si aplicas esta actualización, este paquete tiene problemas de dependencias 

Parece que este paquete requiere "laravel/passport: "^9.0" mientras que Laravel 10 requiere "laravel/passport": "^11.0" y se produce un error en composer update

Muchas gracias de antemano

**Comment by joselfonseca** [comment]
I think that was added here 
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/9.0.0
If we missed support for something else in version 9 then that would be an issue. We may need to have a specific issue for the package we missed.

Lo agregamos aca
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/9.0.0
Si olvidamos soporte a otro paquete en version 9 es un problema. Tendríamos que crear un issue especifico para lo que falta.

**Comment by joselfonseca** [comment]
@elendil1979 Please install version 9 and let us know if it works. 
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/composer.json#L21
It should.

**Comment by elendil1979** [comment]
Perfect, work fine

Thanks
