### ISSUE TITLE
[Suggestion] Add Register User

### ISSUE THREAD

**Issue by dali546** [joselfonseca/lighthouse-graphql-passport-auth#17]
Add default Mutation to register a user.

**Comment by joselfonseca** [comment]
I think is may vary a lot depending on your use case. extracting it here may cause more headaches than help, I'll let the people vote on it so if anyone wants to see this implemented please add a 👍 reaction! Thanks!

**Comment by kandrejevs** [comment]
Laravel comes out of the box with register/login routes, so I guess it makes sense to include them here

**Comment by joselfonseca** [comment]
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/2.0.0
