### ISSUE TITLE
Issue with Laravel 11 which uses Passport 12

### ISSUE THREAD

**Issue by ardito-procoders** [joselfonseca/lighthouse-graphql-passport-auth#178]
I have a problem on my project setup. I am using Laravel 11 and that requires Passport ^12.0.
On your package on the latest version 9.0.2, I see "laravel/passport": "^9.0 || ^10.0 || ^11.0"
On master this is updated to ^12.0 but there is no release.
A release that covers Passport 12 version would be great.

**Comment by sandromedina** [comment]
Hi! I've been waiting for the same feature for a while. Ate teh moment there ars somo pull requests but they cause some tests to fail.

**Comment by joselfonseca** [comment]
New version published from this PR https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/179
