### ISSUE TITLE
RefreshToken resolver doesn't return User model

### ISSUE THREAD

**Issue by zagoruev** [joselfonseca/lighthouse-graphql-passport-auth#18]
Hi,

Scheme describes that refreshToken mutation should return AuthPayload type which respectively should contain non-nullable User.
But RefreshToken resolver returns just credentials.

**Comment by joselfonseca** [comment]
You are correct. I will take a look at this this week. Thanks!

**Comment by zagoruev** [comment]
As we already got tokens, maybe better utilize api/user endpoint over directly querying Eloquent User model?
BTW with this approach we can get rid of 'username' config key.

**Comment by joselfonseca** [comment]
Not really sure what you mean by that, but the refresh token should only need the new tokens, the user info should already be available so i don't really need we need to include it in this response, so I have updated that and the type id

```
type RefreshTokenPayload {
    access_token: String!
    refresh_token: String!
    expires_in: Int!
    token_type: String!
}
```
This will work for refresh tokens. please checkout the latest tag and publish the schema again.

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/1.4.0
