### ISSUE TITLE
PHPUnit Testing 

### ISSUE THREAD

**Issue by imd-solutions** [joselfonseca/lighthouse-graphql-passport-auth#19]
I was wondering how I would test this package with PHPUnit.

I have been stuck on it for a day now. The original message I was getting was:

"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."

Then I realised that it might have something to do with the .env file. I have updated it and added:
 PASSPORT_CLIENT_ID=
PASSPORT_CLIENT_SECRET=

Now I am getting:

"The user credentials were incorrect."

I am guessing this is because of the refreshing of the database. I have tried adding the information manually:

DB::table('oauth_clients')->insert([
           'name' => 'Laravel Password Grant Client',
           'secret' => 'JFOB3ClZdXx5KYICRbNuCC2KlnZjIlX20jHHoWCX',
           'redirect' => 'http://localhost',
           'personal_access_client' => 0,
           'password_client' => 1,
           'revoked' => 0
       ]);

But that still not working, and I would rather not have to add that in every test.

Any help would be appreciated.

*** UPDATE ***

No worries. I have got it working.

**Comment by imd-solutions** [comment]
No worries.

I have got it working.

**Comment by joselfonseca** [comment]
This is what I do for a similar case. May be improved 

```php
public function test_it_gets_passport_tokens()
    {
        $this->installApp();
        $client = Client::create([
            'name' => 'testClient',
            'secret' => 'somesecret',
            'password_client' => 0,
            'revoked' => 0,
            'personal_access_client' => 1,
            'redirect' => 'http://localhost'
        ]);
        config()->set('services.oauth.personal_access_client_id', $client->id);
        config()->set('services.oauth.personal_access_client_secret', $client->secret);
        $user = \App\Entities\User::create([
            'email' => 'jose.luis@example.com',
            'first_name' => 'Jose',
            'last_name' => 'Fonseca',
            'password' => bcrypt('123456789qq')
        ]);
        $this->actingAs($user);
        $tokens = $user->getTokens();
        $this->assertArrayHasKey('access_token', $tokens);
        $this->assertArrayHasKey('refresh_token', $tokens);
        $this->assertArrayHasKey('expires_in', $tokens);
```
