### ISSUE TITLE
Cache store [none] is not defined.

### ISSUE THREAD

**Issue by risestar0927** [joselfonseca/lighthouse-graphql-passport-auth#2]
{
  "errors": [
    {
      "extensions": {
        "guards": []
      },
      "message": "Cache store [none] is not defined.",
      "category": "authentication",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "trace": [
        {
          "file": "E:\\Laravel\\prototype\\app\\Http\\GraphQL\\Mutations\\AccountMutator.php",
          "line": 15,
          "call": "App\\Http\\GraphQL\\Mutations\\BaseAuthResolver::makeRequest(array(5))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\Support\\helpers.php",
          "line": 151,
          "call": "App\\Http\\GraphQL\\Mutations\\AccountMutator::login(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\Schema\\Directives\\Fields\\FieldDirective.php",
          "line": 63,
          "function": "{closure}(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\FieldDirective::Nuwave\\Lighthouse\\Schema\\Directives\\Fields\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\Schema\\Factories\\FieldFactory.php",
          "line": 108,
          "function": "call_user_func_array(instance of Closure, array(4))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\Schema\\Factories\\FieldFactory.php",
          "line": 174,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php",
          "line": 781,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php",
          "line": 744,
          "call": "GraphQL\\Executor\\Executor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php",
          "line": 429,
          "call": "GraphQL\\Executor\\Executor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php",
          "line": 446,
          "call": "GraphQL\\Executor\\Executor::GraphQL\\Executor\\{closure}(array(0), 'login', array(0), GraphQLType: Mutation, null, instance of ArrayObject(1))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Promise\\Adapter\\SyncPromise.php",
          "line": 135,
          "call": "GraphQL\\Executor\\Executor::GraphQL\\Executor\\{closure}(array(0))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Promise\\Adapter\\SyncPromise.php",
          "line": 35,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::GraphQL\\Executor\\Promise\\Adapter\\{closure}()"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\Executor\\Promise\\Adapter\\SyncPromiseAdapter.php",
          "line": 140,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\webonyx\\graphql-php\\src\\GraphQL.php",
          "line": 88,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter::wait(instance of GraphQL\\Executor\\Promise\\Promise)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 113,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  login(data: {username: \"zz\", password: \"zz\"}) {\n    access_token\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Controllers\\GraphQLController.php",
          "line": 83,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  login(data: {username: \"zz\", password: \"zz\"}) {\n    access_token\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Controllers\\GraphQLController.php",
          "line": 62,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::execute(instance of Illuminate\\Http\\Request)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 682,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 684,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 659,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 625,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 614,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 151,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
          "line": 31,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
          "line": 31,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 151,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "E:\\Laravel\\prototype\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\public\\index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "E:\\Laravel\\prototype\\server.php",
          "line": 21,
          "function": "require_once('E:\\Laravel\\prototype\\public\\index.php')"
        }
      ]
    }
  ],
  "data": {
    "login": null
  }
}

When I run lighthouse-graphql-passport-auth/Login mutation I got this error.
Is there anyone resolved this?
Many thanks.

**Comment by joselfonseca** [comment]
It seems the driver for cache is not configured, have you configure cache for Laravel?. This seems to be independent of the package as there is no cache usage in the package itself. Please see if your cache is configured and working properly.

**Comment by risestar0927** [comment]
Yes, that's it.
I missed it.
Thank you.

**Comment by joselfonseca** [comment]
Nice I will close this then.
