### ISSUE TITLE
[FEATURE] Add support for Laravel Socailite

### ISSUE THREAD

**Issue by livevasiliy** [joselfonseca/lighthouse-graphql-passport-auth#21]
Hello @joselfonseca !

I have suggestion add support Laravel Socialite use with Laravel Passport.
Or maybe you can help how to modify your Mutation `login` for set up `grant_type` = `social`, `provider` = for example (`facebook`) & `access_token` from another OAuth application, for example Facebook.

**Comment by joselfonseca** [comment]
Interesting, let me think about it and I get back to you, in the mean time you can modify the mutations to use another resolver and extend this class

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/BaseAuthResolver.php#L8

There you may want to implement the grant. If you get to a solution for this before I do PRs are welcome! 

Thanks for the suggestion.

**Comment by Melcus** [comment]
Having this built in would be nice.

**Comment by joselfonseca** [comment]
Yeah, finding some time to work on this, currently crazy at work.

**Comment by joselfonseca** [comment]
Working this in thee branch https://github.com/joselfonseca/lighthouse-graphql-passport-auth/tree/feature/21-socialite-support

**Comment by joselfonseca** [comment]
Done here https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/47 thanks all!

**Comment by joselfonseca** [comment]
Will be released soon
