### ISSUE TITLE
[Suggestion] Add @spread directive in mutations

### ISSUE THREAD

**Issue by crThiago** [joselfonseca/lighthouse-graphql-passport-auth#22]
Add **@spread** directive in mutations with inputs, so **$args** will contain only the data that matters

### Exemple

> _auth.graphql_

`login(data: LoginInput @spread): AuthPayload!`

**Comment by joselfonseca** [comment]
@crThiago I've added that directive and made a few modifications, will be in the 1.5 release hopefully some time this week. Thanks.

**Comment by joselfonseca** [comment]
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/2.0.0
