### ISSUE TITLE
An unknown error occurred.

### ISSUE THREAD

**Issue by hussainashraf4u** [joselfonseca/lighthouse-graphql-passport-auth#28]
After setting up everything, when trying to login i am getting following errors.
`{
  "errors": [
    {
      "message": "An unknown error occurred.",
      "extensions": {
        "guards": [],
        "category": "authentication"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "trace": [
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\joselfonseca\\lighthouse-graphql-passport-auth\\src\\GraphQL\\Mutations\\Login.php",
          "line": 21,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\BaseAuthResolver::makeRequest(array(5))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\nuwave\\lighthouse\\src\\Schema\\Directives\\FieldDirective.php",
          "line": 68,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\Login::resolve(null, array(3), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\nuwave\\lighthouse\\src\\Schema\\Factories\\FieldFactory.php",
          "line": 225,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\FieldDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 632,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 555,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 478,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 921,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 923,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 494,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 256,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\Executor\\Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\GraphQL.php",
          "line": 158,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\webonyx\\graphql-php\\src\\GraphQL.php",
          "line": 90,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, 'mutation {\n  login(input: {username: \"super@thepostmaster.in\", password: \"9771767747\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n    user {\n      id\n      email\n      name\n      created_at\n      updated_at\n    }\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 177,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  login(input: {username: \"super@thepostmaster.in\", password: \"9771767747\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n    user {\n      id\n      email\n      name\n      created_at\n      updated_at\n    }\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\nuwave\\lighthouse\\src\\GraphQL.php",
          "line": 116,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  login(input: {username: \"super@thepostmaster.in\", password: \"9771767747\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n    user {\n      id\n      email\n      name\n      created_at\n      updated_at\n    }\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Controllers\\GraphQLController.php",
          "line": 70,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeRequest(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 680,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\nuwave\\lighthouse\\src\\Support\\Http\\Middleware\\AcceptJson.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 163,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 682,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 657,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 623,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
          "line": 612,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 163,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\public\\index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\server.php",
          "line": 21,
          "function": "require_once('C:\\Users\\Lenovo\\Desktop\\Bitbucket\\postmaster-api\\public\\index.php')"
        }
      ]
    }
  ]
}`

Please advice.

**Comment by joselfonseca** [comment]
Have you configure passport?

**Comment by kenhyuwa** [comment]
I getting same errors
anyone can solve this?

**Comment by joselfonseca** [comment]
Please make sure

- Passport JS is installed and configured (https://laravel.com/docs/6.x/passport#installation)
- Env vars are set, you can also follow the tutorial (https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5)
- Passport Encryption keys are generated, run `php artisan passport:keys --force`

We've installed this in 4 projects in the last 2 weeks and it works fine. I can only think the passport package is not installed properly.

**Comment by kenhyuwa** [comment]
Thank you very much,
the problem occurred because i used _uuid_ for **primary key**
so all _user_id_ columns for passport tables need to be changed to uuid
