### ISSUE TITLE
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

### ISSUE THREAD

**Issue by gcloares** [joselfonseca/lighthouse-graphql-passport-auth#32]
I have added (Laravel Password Grant Client)
PASSPORT_CLIENT_ID=
PASSPORT_CLIENT_SECRET=
in my .env file, but I keep on getting the error.

Thanks in advance.

**Comment by kandrejevs** [comment]
what is the query you are trying to submit?

**Comment by gcloares** [comment]
This is the query:
mutation {
  login(input: {
    username: "myemail@email.com",
    password: "123456789qq"
  }) {
    access_token
    refresh_token
    expires_in
    token_type
    user {
      id
      email
      name
      created_at
      updated_at
    }
  }
}

I followed the tutorial from here: https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5

**Comment by kandrejevs** [comment]
User type does not have `created_at` and `updated_at` columns

**Comment by gcloares** [comment]
In the tutorial created_at and updated_at are included. 
I'm just trying to make the one in the tutorial work first.

**Comment by helsont** [comment]
I'm getting the same error right now. I'm thinking it might have to do with my primary key being `email` but I'm submitting `username` for the login endpoint.

**Comment by helsont** [comment]
@joselfonseca Correct, I got it to work by making sure that both of the Passport ENVs have values and using `username` instead of `email` when logging in. Also, when defining your User type in Lighthouse's SDL, make sure to use the `@brcrypt` directive in your `createUser` function so that the password is encrypted on save.

**Comment by leoalmar** [comment]
I'm getting the same error.
I fixed at this PR: [https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/33](url)

**Comment by joselfonseca** [comment]
Do you have the @spread directive in your schema definition? https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/graphql/auth.graphql#L60

**Comment by gcloares** [comment]
I redid the tutorial and added the @spread directive. It works now.
I guess @spread solved it.

Thanks!
