### ISSUE TITLE
BUG no se puede cambiar el campo username para encontrar al usuario

### ISSUE THREAD

**Issue by jsamaniegog** [joselfonseca/lighthouse-graphql-passport-auth#35]
Mi config:
```
    /*
    |--------------------------------------------------------------------------
    | Username Column
    |--------------------------------------------------------------------------
    |
    | What column should be use for the username in the users table to find
    | the user.
    |
    */
    'username' => 'username'
```

Query:
```
mutation login {
  login(input: {
    username: "admin",
    password: "secret"
  }) {
    access_token
    refresh_token
    expires_in
    token_type
    user {
      id
      email
      name
      created_at
      updated_at
    }
  }
}
```

Log output:
```
[2019-10-28 15:40:55] local.INFO: "select * from `oauth_clients` where `id` = ? limit 1"
[2019-10-28 15:40:55] local.INFO: ["2"]
[2019-10-28 15:40:55] local.INFO: 38.16
[2019-10-28 15:40:55] local.INFO: "select * from `users` where `email` = ? limit 1"
[2019-10-28 15:40:55] local.INFO: ["admin"]
[2019-10-28 15:40:55] local.INFO: 0.71
[2019-10-28 15:40:55] local.ERROR: The user credentials were incorrect. {"exception":"[object] ...
```

Como puedes ver, está buscando por el campo email en lugar de por username en la SQL.

Un saludo y muchísimas gracias por este estupendo plugin.

**Comment by joselfonseca** [comment]
hola @jsamaniegog Esta configuración también debe aplicarse a passport y al modelo de auth en tu app, esto solo le dice al paquete que columna se usa pero no modifica la configuración de tu laravel App ni la configuración de passport. 

Por favor actualizar esa config y si el problema persiste por favor crear un repo donde pueda reproducir el error y asi poder ayudarte mejor.

Gracias por usar el paquete y saludos desde Colombia!

**Comment by jsamaniegog** [comment]
Perfecto @joselfonseca , he cambiado el campo siguiendo la documentación de Laravel como dice [aquí](https://laravel.com/docs/5.8/passport#customizing-the-username-field) y ha funcionado sin problema.

¡Muchas gracias!
