### ISSUE TITLE
Modify BaseAuthResolver  to get client infos by request

### ISSUE THREAD

**Issue by thoss** [joselfonseca/lighthouse-graphql-passport-auth#38]
Is it possible to modify the BaseAuthResolver so that client_id and client_secret can be used out of the request and get not obtained by the config?

Thanks in advance.

**Comment by joselfonseca** [comment]
Should not be really hard to accomplish, would need a PR here 

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/BaseAuthResolver.php#L19

check if those come in the args if not get them from config. Also will need to add that to the schema. 

I have not come across the use case. If you want to make a PR you are welcome to do so. 

Thanks!

**Comment by joselfonseca** [comment]
Done here https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/47, will be released soon
