### ISSUE TITLE
Laravel 6.2 Client authentication failed

### ISSUE THREAD

**Issue by suonsamoun** [joselfonseca/lighthouse-graphql-passport-auth#41]
```
mutation {
  login(input: {
    username: "root@admin.com",
    password: "1234qwer"
  }) {
    access_token
    refresh_token
    expires_in
    token_type
    user {
      id
      email
      name
      created_at
      updated_at
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Client authentication failed",
      "extensions": {
        "guards": [],
        "category": "authentication"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
```

**Comment by NilsParedes** [comment]
I have the same error, did you get it fixed?

**Comment by joselfonseca** [comment]
Thanks for the issue, This does not give me much info about an acutal problem, I would suggest checking the following

- Passport is installed and keys are generated
- You are using a Passport Password grant client in the .env file
- You set up the client id and secret in the env file for a Password grant client. 

This tutorial should help https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5

**Comment by NilsParedes** [comment]
I just fixed it, your mistake can be the following:

When you run the php artisan passport: install command, in your db in the oauth_clients table copy the id and secret fields of Laravel Password Grant Client and paste them in your .env file as PASSPORT_CLIENT_ID=
PASSPORT_CLIENT_SECRET=

I hope I helped.

**Comment by joselfonseca** [comment]
That is correct, i'll close this and if @suonsamoun has any more issues please report them and we'll do our best to help.

**Comment by jun-gh** [comment]
Hi @joselfonseca , I'm trying to save passport keys as environment variables (in .env), based on this Passport PR https://github.com/laravel/passport/pull/683 .  Is this something that is compatible with this package? TIA

**Comment by joselfonseca** [comment]
hi @jun-gh, If it works on passport it should work on this package, we make an internal request to passport so is the same as if you do the oauth request to the passport routes. We do not change or modify anything on the passport configuration. We only add 2 new grants

**Comment by jun-gh** [comment]
The keys on .env did not work, what we did is save it on AWS s3 bucket,
then copy it on every deploy. But thanks for response.

Martin I. Abanes
miabanes@gmail.com

**Comment by joselfonseca** [comment]
Hey there @jun-gh I just check and we actually use it like that in some production projects. Is weird that it does not work for you. We do have published the passport config file, not sure if that would have something to do but now that I remember part of the process was to publish the Passport config file and add the keys as env vars.
<img width="1285" alt="Screen Shot 2020-09-01 at 7 30 04 AM" src="https://user-images.githubusercontent.com/2046653/91851540-f749ad00-ec24-11ea-8fea-533178670680.png">

**Comment by jun-gh** [comment]
Thanks for getting back to me, I might have miss somewhere. Anyway, It's ok
now that I've save it on s3 bucket and copy on deploy. More power to this
package.


Martin I. Abanes
miabanes@gmail.com
