### ISSUE TITLE
'Credentials were incorrect' error when trying to register

### ISSUE THREAD

**Issue by locent217** [joselfonseca/lighthouse-graphql-passport-auth#42]
I managed to got the login working using username instead of email when I tried the link you gave thanks to that :) . But when I am trying to register another user it says 'Credentials were incorrect' but it was added anyways on the database.

**Comment by joselfonseca** [comment]
@locent217 Have you check that the Password is not being hashed  twice? or that it is actually being hashed? 

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/Register.php#L23

We apply the bcrypt to the password, make sure your model does not have a listener or mutator hasing the password again on save.

**Comment by locent217** [comment]
I don't if it is being hashed by laravel auth.

**Comment by locent217** [comment]
I only added this line:
public function findForPassport($username)
    {
        return $this->where('username', $username)->first();
    }

 on the user model and no other codes are there.

**Comment by locent217** [comment]
@joselfonseca Okay I noticed that the default code of laravel auth on registercontroller has:
'password' => Hash::make($data['password']),
I removed the hash and just make it 'password' => $data['password'], but still the same error

**Comment by joselfonseca** [comment]
Can you please provide a repo where the error happens with the set up.

**Comment by locent217** [comment]
I just put it on the pastebin. here's the link https://pastebin.com/x98CyeFb

I'm sorry for the hassle.

**Comment by locent217** [comment]
@joselfonseca after studying the register.php mutation I noticed the 'email' in the line 27
https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/Register.php#L27
I think this might be the cause because upon reviewing my codes and the register mutation there is no problem with the hashing because I can login to the user and have successful credentials. But when registering a user it still adds the user to the database but upon trying to build credentials it fails because of the line 'username' => $args['email']. 

But that is my understanding, I don't really know what is going on within the credentials part. Thank you for the responses :) I really appreciate the effort of helping me.

**Comment by joselfonseca** [comment]
You are right,  Thanks for reporting this. I will def create a PR for this, this should take the correct configuration value.

**Comment by locent217** [comment]
@joselfonseca  Thanks! :) I am glad that I noticed this. Because I am using laravel-passport and graphql in all of my projects and I admire your work. I hope I will be notified of the latest update soon?
