### ISSUE TITLE
Una duda con los errores

### ISSUE THREAD

**Issue by jsamaniegog** [joselfonseca/lighthouse-graphql-passport-auth#44]
Cuando se hace una solicitud y el token ha expirado se obtiene este error:

`{
  "errors": [
    {
      "debugMessage": "Unauthenticated.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "trace": [
...
}`

Sin embargo, en un entorno de producción la depuración está desactivada (APP_DEBUG=false) y el debugMessage desaparece. ¿Cómo puedo saber desde mi ciente que es un error de autenticación?

Un saludo desde España.

**Comment by argueta15** [comment]
A mi tambien me ayudaria, saber como puedo manejar el error para poder hacer el refresh token y regresar al login en mi aplicacion.

**Comment by joselfonseca** [comment]
Eso depende del middleware utilizado para validar el token. Normalmente sale el mensaje de Unauthenticated o si no puedes hacer esto en el exception handler

```php
if ($exception instanceof AuthenticationException) {
            if (!$request->wantsJson()) {
                return redirect('admin/login');
            }
            $guard = array_get($exception->guards(),0);
                if($guard == 'api') {
                throw new \Nuwave\Lighthouse\Exceptions\AuthenticationException();
            }
        }
```

Basicamente hay que hacer un throw de este exception

```php
throw new \Nuwave\Lighthouse\Exceptions\AuthenticationException();
```

**Comment by jsamaniegog** [comment]
No he conseguido que me funcionara con ese código. Sin embargo, poniendo esto si funciona:
```php
if ($exception instanceof OAuthServerException) {
    throw new \Nuwave\Lighthouse\Exceptions\AuthenticationException();
}
```

Me devuelve esto:
```json
{
  "errors": [
    {
      "message": "Unauthenticated.",
      "extensions": {
        "guards": [],
        "category": "authentication"
      },

```

Con esto me serviría perfectamente, pero, ¿es correcto hacerlo así?

**Comment by joselfonseca** [comment]
Si de hecho esta bien, Yo lo manejo de la otra forma en nuestro scaffold y funciona bien.
