### ISSUE TITLE
Custom Guards

### ISSUE THREAD

**Issue by snetts** [joselfonseca/lighthouse-graphql-passport-auth#5]
Is it possible to use custom guards? My multi-auth has two other custom users not based on Laravels roles but just custom guards. How can you authenticate this kind of users in this kind of configuration?

**Comment by joselfonseca** [comment]
Hello @snetts 

What the package does is use passport to authenticate, by default passport users the user provider, if you can configure passport to use other guards then it will not really depend on this package but passport's configuration. 

Take a look at this, it may help https://medium.com/@jsdecena/laravel-passport-multi-auth-99eb0d6d2efc 

Here is how the package gets the access tokens from passport https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/BaseAuthResolver.php#L26 is like doing a normal request to the token endpoint so at this level no guard is set or configured. I've never really had the need to use different guards TBH so I haven't really created this kind of configuration. But I know is not at this package's level to do so, it is at the Passport configuration level. If you come up with something that may help for it would be nice if you shared it so we see if this package actually needs something to support that.
