### ISSUE TITLE
Error: oauth-private.key does not exist or is not readable

### ISSUE THREAD

**Issue by xbagir** [joselfonseca/lighthouse-graphql-passport-auth#56]
Hi! I get an error when installing the extension on Laravel 6:

![image](https://user-images.githubusercontent.com/621076/72755612-f73bf600-3bdb-11ea-91ff-92dbe3445b47.png)

**Comment by joselfonseca** [comment]
Hey there, please make sure you install and configure Laravel Passport, you can follow this tutorial 

https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5

That basically means you have not installed passport and don't have the Passport keys.

**Comment by joselfonseca** [comment]
What I meant by installing was this

https://laravel.com/docs/6.x/passport#installation

You can install first passport and then this package if that is easier for you. After installing passport following the readme in the repo should straight forward

**Comment by xbagir** [comment]
@joselfonseca 

Right!
But the keys are not stored in the repository (gitignore: /storage/*.key)

So, when a colleague clones my project and does "composer install" it will get this error.
All teams “php artisan xxx” will also return an error.
Deploy also will not work, for similar reasons.

**Comment by joselfonseca** [comment]
what we usually do is for new installations we add this as part of the process

```
Run touch storage/oauth-private.key && touch storage/oauth-public.key
```
Then after installation 
```
php artisan passport:keys --force
```

This is normal with passport, Keys should not be versioned. They should be generated in the environment or as part of a CI / CD pipeline. You can also use the Env vars to set those keys. But this is more a Passport related procedure and is outside of the scope of this package as it depends on passport and it states that Passport should be installed and configured for this to work.

**Comment by xbagir** [comment]
@joselfonseca 
Thank you!
