### ISSUE TITLE
Cannot run commands when oauth keys are not present

### ISSUE THREAD

**Issue by ChrisTemper** [joselfonseca/lighthouse-graphql-passport-auth#57]
Hello,

When I've got not passport keys yet in my project and the `LighthouseGraphQLPassportServiceProvider` is being booted I got an error:
```
Key path "storage/oauth-private.key" does not exist or is not readable
```

When i try to run the `php artisan passport:keys` command to generate these keys i still got the same error because it is already trying to do something with these keys.

Line that gives the error: `LighthouseGraphQLPassportServiceProvider.php:28`

Is there a way to fix this?

**Comment by joselfonseca** [comment]
Hello there, 

So this is the reason why is a pre requisite that the Laravel Passport package is pre installed and configured before trying to use this one.

What we usually do is for new installations we add this as part of the process

```
Run touch storage/oauth-private.key && touch storage/oauth-public.key
```

Then after installation

```
php artisan passport:keys --force
```

This is normal with passport, Keys should not be versioned.

**Comment by ChrisTemper** [comment]
Hi Jose,

Thanks for the answer i will try that in my CI to fix the issue.

**Comment by joselfonseca** [comment]
I have in the readme 

**Make sure you have Laravel Passport installed.**

Maybe I need to be more explicit about this.

Also there is a Tutorial available if it helps

https://dev.to/joselfonseca/graphql-auth-with-passport-and-lighthouse-php-14g5

**Comment by ChrisTemper** [comment]
I see, i was hoping i didn't need to touch any files ;)
