### ISSUE TITLE
How to refreshToken on the frontend when expired

### ISSUE THREAD

**Issue by 7ammer** [joselfonseca/lighthouse-graphql-passport-auth#6]
Hello,

Sorry to be asking here but I hope you can help.

I was just wondering how you would recommend refreshing an access_token before it expires.

I'm guessing that the suggested method here is to store both the access_token and the refresh_token on the client side. When the access_token expires you can use the refresh_token to get a new access_token.

However I have read that storing the refresh_token in the browser is a bad idea as a hacker could use it to continually refresh a token indefinitely.

Is the above what you would recommend with this library or do you recommend something else?

I did notice this which prevents sending the actual tokens https://laravel.com/docs/5.7/passport#consuming-your-api-with-javascript
but it doesn't quite fit with graphql and doesn't resolve how to renew expired tokens.

**Comment by emielmolenaar** [comment]
I have used https://github.com/websanova/vue-auth to handle this kind of stuff on the frontend, but never in combination with GraphQL. I guess one needs a HTTP driver for that (https://github.com/websanova/vue-auth/tree/master/drivers/http) .

**Comment by joselfonseca** [comment]
You can store the refresh token in local or session storage and use this mutation to refresh it when the access_token expires

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/graphql/auth.graphql#L40

**Comment by tnerbovik** [comment]
I don't think it's normally a good practise to store refresh token in localStorage. A better option is to let the auth server return refresh token only as a httpOnly cookie. At least use Content Security Policy.

PS: great package, btw. Looking forward to test it
