### ISSUE TITLE
Login auth grant problem..

### ISSUE THREAD

**Issue by SamSebastien** [joselfonseca/lighthouse-graphql-passport-auth#63]
Hi there, I read through your blog post regarding setup, and the instructions in this repo but when I attempt to login as per the blog post, I get the following error:

`The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.`

```json
{
	"message": "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
	"extensions": {
		"guards": [],
		"category": "authentication"
	},
	"locations": [
		{
			"line": 2,
			"column": 3
		}
	],
	"path": [
		"login"
	]
}
```

For reference, I am using Homestead for development currently so not sure if this is an issue?

This is where the error trace stops:

`> /joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/Login.php`
`> BaseAuthResolver::makeRequest(array(5))`

```json
"trace": [
	{
		"file": "/home/vagrant/App/vendor/joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/Login.php",
		"line": 23,
		"call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\BaseAuthResolver::makeRequest(array(5))"
	}
]
```

Any obvious errors that I am making?

**Comment by joselfonseca** [comment]
@SamSebastien Hi there, Last time I saw this message the issue was that the client id and secret were not correct, are you using the password grant client?

**Comment by SamSebastien** [comment]
Yes, I just moments ago realised I wasn't bcrypting the password on the user I was setting up.. urgh sorry!

**Comment by joselfonseca** [comment]
@SamSebastien Don't worry! glad it was fixed!
