### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by nateajohnson** [joselfonseca/lighthouse-graphql-passport-auth#69]
Any chance the composer file can get updated so this framework works with Laravel 7?

**Comment by joselfonseca** [comment]
Yes, working on it! I am checking if Lighthouse PHP is ready for it but it seems I have to wait for this one

https://github.com/nuwave/lighthouse/pull/1219

Once this is merged I will update this package as well

**Comment by nateajohnson** [comment]
I pulled in the new version of lighthouse that supports Laravel 7 and am now seeing this error. You are likely still working on your library, but just wanted to let you know about it.

`[2020-03-05 20:06:55] local.ERROR: Trait 'Illuminate\Foundation\Auth\SendsPasswordResetEmails' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Trait 'Illuminate\\Foundation\\Auth\\SendsPasswordResetEmails' not found at .../vendor/joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/ForgotPassword.php:12)`

**Comment by normanaranez** [comment]
is the library support laravel 7 or you still working on this? just let us know when is this available

**Comment by joselfonseca** [comment]
I am working on this today, hopfully a new release will be out EOD with Laravel 7 support and a middleware to set the logged in user since the middleware directive was deprecated.

**Comment by joselfonseca** [comment]
Done https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/4.0.0

**Comment by joselfonseca** [comment]
I forgot the middleware, will create a new release for that one. Sorry
