### ISSUE TITLE
Suggestion: Allow User model to be included in auth payload response

### ISSUE THREAD

**Issue by SirLamer** [joselfonseca/lighthouse-graphql-passport-auth#7]
After logging in via API it will be commonly necessary to obtain the user account data "name, email, thumbnail URL, etc" for UI display purposes. I suggest that the AuthPayload ought to include the User model associated with the token in the response. Right now I am querying the User separately after auth which is kinda silly.

**Comment by joselfonseca** [comment]
This is a good one, let's put it as a feature request and think about how to implement it.

**Comment by joselfonseca** [comment]
@SirLamer added it in https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/1.3.0
