### ISSUE TITLE
Login error message is too generic.

### ISSUE THREAD

**Issue by mlab817** [joselfonseca/lighthouse-graphql-passport-auth#75]
Currently, any error that occur when trying to login is only

`The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.`

I understand that we do not want to expose errors to users but I think that errors should be categorized like so:

1) Email or password is incorrect.
2) Invalid passport oauth key.
3) Other errors.

Anyway, I'm already working on my own solution at the moment. Just wanted to bring this up for succeeding versions of this package.

Thanks for the good work!

**Comment by joselfonseca** [comment]
Hey @hosmelq I actually want to fix this, how did you solve it?
