### ISSUE TITLE
The _() or getText function in UpdatePassword mutation is throwing undefined error

### ISSUE THREAD

**Issue by mlab817** [joselfonseca/lighthouse-graphql-passport-auth#76]
The title says it all. It seems that my version of PHP or server does not support this alias. I am using heroku hosting and php version 7.2. Well, for now, I just copied the update password mutation in my App/GraphQL/Mutations directory and removed instances of the function.

Any ideas on how to properly address this as I don't want to tamper on the package. It makes it hard to update. Thanks!

**Comment by joselfonseca** [comment]
@mlab817 I actually have 7.2 test in travis, can you please show me a more specific error in order to have a better idea of what is going on?

**Comment by mlab817** [comment]
Here's the full error:

`{
  "errors": [
    {
      "debugMessage": "Call to undefined function Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\_()",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updatePassword"
      ],
      "trace": [
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Schema/Directives/FieldDirective.php",
          "line": 58,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\UpdatePassword::resolve()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Schema/Directives/GuardDirective.php",
          "line": 74,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\FieldDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 174,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\GuardDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 632,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 555,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 478,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 921,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}()"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 923,
          "function": "array_reduce()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 494,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 256,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 158,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 90,
          "call": "GraphQL\\GraphQL::promiseToExecute()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 171,
          "call": "GraphQL\\GraphQL::executeQuery()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 110,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 70,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeRequest()"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 681,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 130,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}()"
        },
        {
          "file": "/app/vendor/joselfonseca/lighthouse-graphql-passport-auth/src/Http/Middleware/AuthenticateWithApiGuard.php",
          "line": 38,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\Http\\Middleware\\AuthenticateWithApiGuard::handle()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php",
          "line": 30,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 105,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 683,
          "call": "Illuminate\\Pipeline\\Pipeline::then()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 658,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 624,
          "call": "Illuminate\\Routing\\Router::runRoute()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 613,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 170,
          "call": "Illuminate\\Routing\\Router::dispatch()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 130,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}()"
        },
        {
          "file": "/app/vendor/barryvdh/laravel-cors/src/HandleCors.php",
          "line": 58,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Barryvdh\\Cors\\HandleCors::handle()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 63,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle()"
        },
        {
          "file": "/app/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Fideloper\\Proxy\\TrustProxies::handle()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 105,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 145,
          "call": "Illuminate\\Pipeline\\Pipeline::then()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 110,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter()"
        },
        {
          "file": "/app/public/index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle()"
        }
      ]
    }
  ],
  "extensions": {
    "lighthouse_subscriptions": {
      "version": 1,
      "channels": []
    }
  }
}`

**Comment by joselfonseca** [comment]
This seems to be a problem with Heroku run time as the function `_()` is isntalled with the `getText` extension 

Can you please verify that this extension is available in the runtime? 
https://stackoverflow.com/questions/43690687/php-gettext-installed-but-not-available

Not able to reproduce.

**Comment by mlab817** [comment]
Thanks. Enabling gettext extension in circleCI build fixed the problem. It is not being enabled by default. To those who will come across the problem, just enable the php extension gettext because it is not enabled by default.
