### ISSUE TITLE
Email verification is sent twice

### ISSUE THREAD

**Issue by mlab817** [joselfonseca/lighthouse-graphql-passport-auth#77]
I still don't know what's causing it but my application is sending email verification twice. I tried removing **MustVerifyEmail** and **MustVerifyEmailGraphQL** from AppUser model but it still continues doing so. This is not just a case of simple duplication of email. The verification is sent twice with different tokens which means that the notification (sendEmailVerificationNotification) is being called twice. 

Upon inspection, the package calls the following in the Register resolver:

```php
if ($model instanceof MustVerifyEmail) {
   // called by package
    $model->sendEmailVerificationNotification();

    event(new Registered($model));

    return [
         'tokens' => [],
         'status' => 'MUST_VERIFY_EMAIL',
    ];
}
```

Is this a bug?

**Comment by joselfonseca** [comment]
hey there, there should be a event listener in your EventServiceProvider registered as well, it comes default with laravel. I think I should add to the docs that you have to remove it or this will happen. Please check that listener and removed from event service provider.

**Comment by mlab817** [comment]
Thanks. Found it. In the EventServiceProvider file there is also a listener for registered event:
```php
Registered::class => [
     SendEmailVerificationNotification::class,
],
```

I also think it should be added in the docs to avoid future problems.
