### ISSUE TITLE
Add Remove email verification event to docs

### ISSUE THREAD

**Issue by joselfonseca** [joselfonseca/lighthouse-graphql-passport-auth#78]
Context: https://github.com/joselfonseca/lighthouse-graphql-passport-auth/issues/77

**Comment by BilalBasha** [comment]
Hello. I was stuck in verify the email concept.

input VerifyEmailInput {
    token: String!
}

Which token I have to use here...?

**Comment by joselfonseca** [comment]
Hello, the email sent will have a token in the url. Usually we use it to open the app grab the tokens and send it in the mutation. Look for the token in the url sent in the email.

**Comment by BilalBasha** [comment]
Yes, I tried that, that one throws below error. Please check

![image](https://user-images.githubusercontent.com/24795092/79694748-ee68c800-828f-11ea-9806-b2b10fa690ec.png)

**Comment by joselfonseca** [comment]
Make sure you are not using the email sent by default by laravel, remove the listener that comes in default with laravel and let this package send the notification

**Comment by joselfonseca** [comment]
Done, Added here https://lighthouse-passport-auth.web.app/docs/usage/#email-verification
