### ISSUE TITLE
Cannot use login mutation

### ISSUE THREAD

**Issue by hamitg** [joselfonseca/lighthouse-graphql-passport-auth#84]
I cannot use login mutation, it gives the following errors
![Screen Shot 2020-04-28 at 11 14 19](https://user-images.githubusercontent.com/33285391/80463891-9d1ca080-8941-11ea-8aea-f0b43c7fa838.png)
![Screen Shot 2020-04-28 at 11 15 05](https://user-images.githubusercontent.com/33285391/80463907-a443ae80-8941-11ea-89da-ce0a29148f3f.png)

**Comment by joselfonseca** [comment]
That is because the argument is input not data

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/graphql/auth.graphql#L90
