### ISSUE TITLE
Need Laravel 7 and passport 9 support.

### ISSUE THREAD

**Issue by sujitrulz** [joselfonseca/lighthouse-graphql-passport-auth#89]
Hi I was wondering if there will be a support for  "laravel/framework": "^7.0",, "laravel/passport": "^9.0", ?  Help Appreciated.

**Comment by joselfonseca** [comment]
Hello there, yes, at the time of this writing the version 9 of passport was released 18 hours ago. i'll find some time to update the composer.json.

PRs are welcome! I don't think there is too much change other than updating the composer.json

**Comment by ZenelShabani** [comment]
@joselfonseca Great work man! When can we expect support for passport v9 ?+-
I just upgraded the passport package and kinda stuck now, if u can give me an estimate I can decide if I'll wait or just rollback to v8

Thanks in advance!

**Comment by joselfonseca** [comment]
Please see

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/4.1.11
