### ISSUE TITLE
Which events should I listen to keep track of login, logout activites ?

### ISSUE THREAD

**Issue by canatufkansu** [joselfonseca/lighthouse-graphql-passport-auth#92]
Hi,

I'm implementing Spatie's Activity Log (https://github.com/spatie/laravel-activitylog) to keep track of all Auth activities in the API. Which events should I listen for Login, Logout, RefreshToken, Register, ForgotPassword and UpdatePassword ?

If I could listen Failed Login and Failed Update Password attempts that would be great.

Thanks,

**Comment by joselfonseca** [comment]
working this on this branch https://github.com/joselfonseca/lighthouse-graphql-passport-auth/tree/feature/adding-events

**Comment by joselfonseca** [comment]
Added this events

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/106

It will be released on 5.0 with a few other changes.
