### ISSUE TITLE
ValidatesRequests not found

### ISSUE THREAD

**Issue by aurigadl** [joselfonseca/lighthouse-graphql-passport-auth#93]
I am using the library with Lumen. The Illuminate \ Foundation \ Validation \ ValidatesRequests' resource is not in lumen and the ResetPassword Mutation requests this resource (ValidatesRequests) that is not being used.
If that dependency that is not being used can be deleted, it would help to not generate the error in lumen and we would not have to rewrite that mutation.

> ` POST /graphql - Trait 'Illuminate\Foundation\Validation\ValidatesRequests'  not found in `

composer.json
```
    "require": {
        "php": "^7.2.5",
        "dusterio/lumen-passport": "^0.2.19",
        "joselfonseca/lighthouse-graphql-passport-auth": "^4.1",
        "laravel/lumen-framework": "^7.0",
        "nuwave/lighthouse": "^4.13"
    },
```

**Comment by joselfonseca** [comment]
Hey @aurigadl. I've never used Lumen so I never came across this. 

Can you try this https://github.com/joselfonseca/lighthouse-graphql-passport-auth/releases/tag/4.1.12 and see if that fixes the lumen compatibility

**Comment by aurigadl** [comment]
Thanks, it is already working, the error no longer appears in lumen.
