### ISSUE TITLE
Como se usa el paquete de autenticación por Facebook o Google

### ISSUE THREAD

**Issue by devrheber** [joselfonseca/lighthouse-graphql-passport-auth#97]
Hola, estoy utilizando tu librería para poder usar la autenticación en graphql y lighthouse el problema es el siguiente:

Tengo una App móvil que consume la App y hace el registro, en este caso como haría la integración ?

**Comment by joselfonseca** [comment]
El app mobil usa los SDK de login de los proveedores de auth. Luego envia el proveedor y el access token en la mutation social login. el API le da un token si puede usar ese access token en el proveedor de auth. Para eso socialite debe estar configurado para la red social a usar.
