### ISSUE TITLE
Social Login breaks if user signed up via email

### ISSUE THREAD

**Issue by akshitkrnagpal** [joselfonseca/lighthouse-graphql-passport-auth#98]
**What is happening now**
Since the user signed up using email, the provider field is null and hence it tries to create an account, which also fails because email is already present. 

**What is expected**
When user login via Facebook, instead of throwing the error it should update the provider and provider_id if they are null.

BTW. Awesome work. Thanks. ❤️

**Comment by dinhkhanh** [comment]
This is nice to have.
User may registered by email, later on they would like to login by Social accounts.
Or in Account Settings page, they would like to connect their Social accounts.

It should automatically match their email-based account with Social ones.

**Comment by joselfonseca** [comment]
PRs are welcome!

**Comment by th3error** [comment]
I just ran into this yesterday. I fixed it by simply checking whether the user's email exists but the `provider` & `provider_id` are not matching that of the request, which in my case means they're empty. I only use Facebook for social login in my app so these fields either have data or they don't. If the email is there, I update that user and add the `provider` and `provider_id`.

This is done before the Try Catch. I can submit a PR, but I don't think this solution would accomidate more than one provider/user.

**Comment by akshitkrnagpal** [comment]
> I fixed it by simply checking whether the user's email exists but the provider & provider_id are not matching that of the request, which in my case means they're empty. 

Yes. This is exactly what I do in my app. 

-----------------------------------

@joselfonseca I see you have self-assigned yourself. May I ask what scope do you have in mind? Ideally, we would like to connect multiple social accounts to a single user.

**Comment by joselfonseca** [comment]
@akshitkrnagpal I was thinking on supporting multiple although I never had that use case before. Usually only one was required. I removed the assignation in case anyone wants to work on it since I haven't had a lot of time

**Comment by joselfonseca** [comment]
This is addressed in the PR https://github.com/joselfonseca/lighthouse-graphql-passport-auth/pull/130. However it includes a breaking change for good.
